// Code generated by radius-dict-gen. DO NOT EDIT.

package threegpp

import (
	"net"
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_ThreeGPP_VendorID = 10415
)

func _ThreeGPP_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_ThreeGPP_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _ThreeGPP_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, attr := range p.Attributes[rfc2865.VendorSpecific_Type] {
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _ThreeGPP_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _ThreeGPP_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, a := range p.Attributes[rfc2865.VendorSpecific_Type] {
		vendorID, vsa, err := radius.VendorSpecific(a)
		if err != nil || vendorID != _ThreeGPP_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _ThreeGPP_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes[rfc2865.VendorSpecific_Type]); {
		vendorID, vsa, err := radius.VendorSpecific(p.Attributes[rfc2865.VendorSpecific_Type][i])
		if err != nil || vendorID != _ThreeGPP_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(p.Attributes[rfc2865.VendorSpecific_Type][i][4:], vsa)
			i++
		} else {
			p.Attributes[rfc2865.VendorSpecific_Type] = append(p.Attributes[rfc2865.VendorSpecific_Type][:i], p.Attributes[rfc2865.VendorSpecific_Type][i+i:]...)
		}
	}
	return _ThreeGPP_AddVendor(p, typ, attr)
}

func _ThreeGPP_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes[rfc2865.VendorSpecific_Type]); {
		attr := p.Attributes[rfc2865.VendorSpecific_Type][i]
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _ThreeGPP_VendorID {
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes[rfc2865.VendorSpecific_Type] = append(p.Attributes[rfc2865.VendorSpecific_Type][:i], p.Attributes[rfc2865.VendorSpecific_Type][i+1:]...)
		} else {
			i++
		}
	}
	return
}

func ThreeGPPIMSI_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 1, a)
}

func ThreeGPPIMSI_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 1, a)
}

func ThreeGPPIMSI_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPIMSI_Lookup(p)
	return
}

func ThreeGPPIMSI_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPIMSI_LookupString(p)
	return
}

func ThreeGPPIMSI_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 1) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIMSI_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 1) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIMSI_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPIMSI_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPIMSI_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 1, a)
}

func ThreeGPPIMSI_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 1, a)
}

func ThreeGPPIMSI_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 1)
}

type ThreeGPPChargingID uint32

var ThreeGPPChargingID_Strings = map[ThreeGPPChargingID]string{}

func (a ThreeGPPChargingID) String() string {
	if str, ok := ThreeGPPChargingID_Strings[a]; ok {
		return str
	}
	return "ThreeGPPChargingID(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ThreeGPPChargingID_Add(p *radius.Packet, value ThreeGPPChargingID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_AddVendor(p, 2, a)
}

func ThreeGPPChargingID_Get(p *radius.Packet) (value ThreeGPPChargingID) {
	value, _ = ThreeGPPChargingID_Lookup(p)
	return
}

func ThreeGPPChargingID_Gets(p *radius.Packet) (values []ThreeGPPChargingID, err error) {
	var i uint32
	for _, attr := range _ThreeGPP_GetsVendor(p, 2) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ThreeGPPChargingID(i))
	}
	return
}

func ThreeGPPChargingID_Lookup(p *radius.Packet) (value ThreeGPPChargingID, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ThreeGPPChargingID(i)
	return
}

func ThreeGPPChargingID_Set(p *radius.Packet, value ThreeGPPChargingID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_SetVendor(p, 2, a)
}

func ThreeGPPChargingID_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 2)
}

type ThreeGPPPDPType uint32

const (
	ThreeGPPPDPType_Value_IPv4   ThreeGPPPDPType = 0
	ThreeGPPPDPType_Value_PPP    ThreeGPPPDPType = 1
	ThreeGPPPDPType_Value_IPv6   ThreeGPPPDPType = 2
	ThreeGPPPDPType_Value_IPv4v6 ThreeGPPPDPType = 3
)

var ThreeGPPPDPType_Strings = map[ThreeGPPPDPType]string{
	ThreeGPPPDPType_Value_IPv4:   "IPv4",
	ThreeGPPPDPType_Value_PPP:    "PPP",
	ThreeGPPPDPType_Value_IPv6:   "IPv6",
	ThreeGPPPDPType_Value_IPv4v6: "IPv4v6",
}

func (a ThreeGPPPDPType) String() string {
	if str, ok := ThreeGPPPDPType_Strings[a]; ok {
		return str
	}
	return "ThreeGPPPDPType(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ThreeGPPPDPType_Add(p *radius.Packet, value ThreeGPPPDPType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_AddVendor(p, 3, a)
}

func ThreeGPPPDPType_Get(p *radius.Packet) (value ThreeGPPPDPType) {
	value, _ = ThreeGPPPDPType_Lookup(p)
	return
}

func ThreeGPPPDPType_Gets(p *radius.Packet) (values []ThreeGPPPDPType, err error) {
	var i uint32
	for _, attr := range _ThreeGPP_GetsVendor(p, 3) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ThreeGPPPDPType(i))
	}
	return
}

func ThreeGPPPDPType_Lookup(p *radius.Packet) (value ThreeGPPPDPType, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ThreeGPPPDPType(i)
	return
}

func ThreeGPPPDPType_Set(p *radius.Packet, value ThreeGPPPDPType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_SetVendor(p, 3, a)
}

func ThreeGPPPDPType_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 3)
}

func ThreeGPPChargingGatewayAddress_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 4, a)
}

func ThreeGPPChargingGatewayAddress_Get(p *radius.Packet) (value net.IP) {
	value, _ = ThreeGPPChargingGatewayAddress_Lookup(p)
	return
}

func ThreeGPPChargingGatewayAddress_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _ThreeGPP_GetsVendor(p, 4) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPChargingGatewayAddress_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 4)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ThreeGPPChargingGatewayAddress_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 4, a)
}

func ThreeGPPChargingGatewayAddress_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 4)
}

func ThreeGPPGPRSNegotiatedQoSProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 5, a)
}

func ThreeGPPGPRSNegotiatedQoSProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 5, a)
}

func ThreeGPPGPRSNegotiatedQoSProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPGPRSNegotiatedQoSProfile_Lookup(p)
	return
}

func ThreeGPPGPRSNegotiatedQoSProfile_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPGPRSNegotiatedQoSProfile_LookupString(p)
	return
}

func ThreeGPPGPRSNegotiatedQoSProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 5) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPGPRSNegotiatedQoSProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 5) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPGPRSNegotiatedQoSProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 5)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPGPRSNegotiatedQoSProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 5)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPGPRSNegotiatedQoSProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 5, a)
}

func ThreeGPPGPRSNegotiatedQoSProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 5, a)
}

func ThreeGPPGPRSNegotiatedQoSProfile_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 5)
}

func ThreeGPPSGSNAddress_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 6, a)
}

func ThreeGPPSGSNAddress_Get(p *radius.Packet) (value net.IP) {
	value, _ = ThreeGPPSGSNAddress_Lookup(p)
	return
}

func ThreeGPPSGSNAddress_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _ThreeGPP_GetsVendor(p, 6) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSGSNAddress_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 6)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ThreeGPPSGSNAddress_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 6, a)
}

func ThreeGPPSGSNAddress_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 6)
}

func ThreeGPPGGSNAddress_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 7, a)
}

func ThreeGPPGGSNAddress_Get(p *radius.Packet) (value net.IP) {
	value, _ = ThreeGPPGGSNAddress_Lookup(p)
	return
}

func ThreeGPPGGSNAddress_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _ThreeGPP_GetsVendor(p, 7) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPGGSNAddress_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 7)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ThreeGPPGGSNAddress_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 7, a)
}

func ThreeGPPGGSNAddress_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 7)
}

func ThreeGPPIMSIMCCMNC_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 8, a)
}

func ThreeGPPIMSIMCCMNC_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 8, a)
}

func ThreeGPPIMSIMCCMNC_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPIMSIMCCMNC_Lookup(p)
	return
}

func ThreeGPPIMSIMCCMNC_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPIMSIMCCMNC_LookupString(p)
	return
}

func ThreeGPPIMSIMCCMNC_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 8) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIMSIMCCMNC_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 8) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIMSIMCCMNC_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 8)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPIMSIMCCMNC_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 8)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPIMSIMCCMNC_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 8, a)
}

func ThreeGPPIMSIMCCMNC_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 8, a)
}

func ThreeGPPIMSIMCCMNC_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 8)
}

func ThreeGPPGGSNMCCMNC_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 9, a)
}

func ThreeGPPGGSNMCCMNC_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 9, a)
}

func ThreeGPPGGSNMCCMNC_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPGGSNMCCMNC_Lookup(p)
	return
}

func ThreeGPPGGSNMCCMNC_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPGGSNMCCMNC_LookupString(p)
	return
}

func ThreeGPPGGSNMCCMNC_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 9) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPGGSNMCCMNC_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 9) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPGGSNMCCMNC_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 9)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPGGSNMCCMNC_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 9)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPGGSNMCCMNC_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 9, a)
}

func ThreeGPPGGSNMCCMNC_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 9, a)
}

func ThreeGPPGGSNMCCMNC_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 9)
}

func ThreeGPPNSAPI_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 10, a)
}

func ThreeGPPNSAPI_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 10, a)
}

func ThreeGPPNSAPI_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPNSAPI_Lookup(p)
	return
}

func ThreeGPPNSAPI_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPNSAPI_LookupString(p)
	return
}

func ThreeGPPNSAPI_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 10) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPNSAPI_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 10) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPNSAPI_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 10)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPNSAPI_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 10)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPNSAPI_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 10, a)
}

func ThreeGPPNSAPI_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 10, a)
}

func ThreeGPPNSAPI_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 10)
}

func ThreeGPPSessionStopIndicator_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 11, a)
}

func ThreeGPPSessionStopIndicator_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 11, a)
}

func ThreeGPPSessionStopIndicator_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPSessionStopIndicator_Lookup(p)
	return
}

func ThreeGPPSessionStopIndicator_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPSessionStopIndicator_LookupString(p)
	return
}

func ThreeGPPSessionStopIndicator_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 11) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSessionStopIndicator_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 11) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSessionStopIndicator_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 11)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPSessionStopIndicator_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 11)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPSessionStopIndicator_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 11, a)
}

func ThreeGPPSessionStopIndicator_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 11, a)
}

func ThreeGPPSessionStopIndicator_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 11)
}

func ThreeGPPSelectionMode_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 12, a)
}

func ThreeGPPSelectionMode_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 12, a)
}

func ThreeGPPSelectionMode_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPSelectionMode_Lookup(p)
	return
}

func ThreeGPPSelectionMode_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPSelectionMode_LookupString(p)
	return
}

func ThreeGPPSelectionMode_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 12) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSelectionMode_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 12) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSelectionMode_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPSelectionMode_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPSelectionMode_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 12, a)
}

func ThreeGPPSelectionMode_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 12, a)
}

func ThreeGPPSelectionMode_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 12)
}

func ThreeGPPChargingCharacteristics_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 13, a)
}

func ThreeGPPChargingCharacteristics_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 13, a)
}

func ThreeGPPChargingCharacteristics_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPChargingCharacteristics_Lookup(p)
	return
}

func ThreeGPPChargingCharacteristics_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPChargingCharacteristics_LookupString(p)
	return
}

func ThreeGPPChargingCharacteristics_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 13) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPChargingCharacteristics_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 13) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPChargingCharacteristics_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPChargingCharacteristics_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPChargingCharacteristics_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 13, a)
}

func ThreeGPPChargingCharacteristics_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 13, a)
}

func ThreeGPPChargingCharacteristics_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 13)
}

func ThreeGPPChargingGatewayIPv6Address_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPv6Addr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 14, a)
}

func ThreeGPPChargingGatewayIPv6Address_Get(p *radius.Packet) (value net.IP) {
	value, _ = ThreeGPPChargingGatewayIPv6Address_Lookup(p)
	return
}

func ThreeGPPChargingGatewayIPv6Address_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _ThreeGPP_GetsVendor(p, 14) {
		i, err = radius.IPv6Addr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPChargingGatewayIPv6Address_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 14)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPv6Addr(a)
	return
}

func ThreeGPPChargingGatewayIPv6Address_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPv6Addr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 14, a)
}

func ThreeGPPChargingGatewayIPv6Address_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 14)
}

func ThreeGPPSGSNIPv6Address_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPv6Addr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 15, a)
}

func ThreeGPPSGSNIPv6Address_Get(p *radius.Packet) (value net.IP) {
	value, _ = ThreeGPPSGSNIPv6Address_Lookup(p)
	return
}

func ThreeGPPSGSNIPv6Address_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _ThreeGPP_GetsVendor(p, 15) {
		i, err = radius.IPv6Addr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSGSNIPv6Address_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPv6Addr(a)
	return
}

func ThreeGPPSGSNIPv6Address_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPv6Addr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 15, a)
}

func ThreeGPPSGSNIPv6Address_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 15)
}

func ThreeGPPGGSNIPv6Address_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPv6Addr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 16, a)
}

func ThreeGPPGGSNIPv6Address_Get(p *radius.Packet) (value net.IP) {
	value, _ = ThreeGPPGGSNIPv6Address_Lookup(p)
	return
}

func ThreeGPPGGSNIPv6Address_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _ThreeGPP_GetsVendor(p, 16) {
		i, err = radius.IPv6Addr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPGGSNIPv6Address_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 16)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPv6Addr(a)
	return
}

func ThreeGPPGGSNIPv6Address_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPv6Addr(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 16, a)
}

func ThreeGPPGGSNIPv6Address_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 16)
}

func ThreeGPPIPv6DNSServers_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 17, a)
}

func ThreeGPPIPv6DNSServers_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 17, a)
}

func ThreeGPPIPv6DNSServers_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPIPv6DNSServers_Lookup(p)
	return
}

func ThreeGPPIPv6DNSServers_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPIPv6DNSServers_LookupString(p)
	return
}

func ThreeGPPIPv6DNSServers_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 17) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIPv6DNSServers_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 17) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIPv6DNSServers_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 17)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPIPv6DNSServers_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 17)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPIPv6DNSServers_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 17, a)
}

func ThreeGPPIPv6DNSServers_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 17, a)
}

func ThreeGPPIPv6DNSServers_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 17)
}

func ThreeGPPSGSNMCCMNC_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 18, a)
}

func ThreeGPPSGSNMCCMNC_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 18, a)
}

func ThreeGPPSGSNMCCMNC_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPSGSNMCCMNC_Lookup(p)
	return
}

func ThreeGPPSGSNMCCMNC_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPSGSNMCCMNC_LookupString(p)
	return
}

func ThreeGPPSGSNMCCMNC_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 18) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSGSNMCCMNC_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 18) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPSGSNMCCMNC_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 18)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPSGSNMCCMNC_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 18)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPSGSNMCCMNC_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 18, a)
}

func ThreeGPPSGSNMCCMNC_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 18, a)
}

func ThreeGPPSGSNMCCMNC_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 18)
}

func ThreeGPPTeardownIndicator_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 19, a)
}

func ThreeGPPTeardownIndicator_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 19, a)
}

func ThreeGPPTeardownIndicator_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPTeardownIndicator_Lookup(p)
	return
}

func ThreeGPPTeardownIndicator_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPTeardownIndicator_LookupString(p)
	return
}

func ThreeGPPTeardownIndicator_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 19) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPTeardownIndicator_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 19) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPTeardownIndicator_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 19)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPTeardownIndicator_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 19)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPTeardownIndicator_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 19, a)
}

func ThreeGPPTeardownIndicator_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 19, a)
}

func ThreeGPPTeardownIndicator_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 19)
}

func ThreeGPPIMEISV_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 20, a)
}

func ThreeGPPIMEISV_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 20, a)
}

func ThreeGPPIMEISV_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPIMEISV_Lookup(p)
	return
}

func ThreeGPPIMEISV_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPIMEISV_LookupString(p)
	return
}

func ThreeGPPIMEISV_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 20) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIMEISV_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 20) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPIMEISV_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 20)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPIMEISV_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 20)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPIMEISV_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 20, a)
}

func ThreeGPPIMEISV_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 20, a)
}

func ThreeGPPIMEISV_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 20)
}

type ThreeGPPRATType uint32

const (
	ThreeGPPRATType_Value_Reserved       ThreeGPPRATType = 0
	ThreeGPPRATType_Value_UTRAN          ThreeGPPRATType = 1
	ThreeGPPRATType_Value_GERAN          ThreeGPPRATType = 2
	ThreeGPPRATType_Value_WLAN           ThreeGPPRATType = 3
	ThreeGPPRATType_Value_GAN            ThreeGPPRATType = 4
	ThreeGPPRATType_Value_HSPAEvolution  ThreeGPPRATType = 5
	ThreeGPPRATType_Value_EUTRAN         ThreeGPPRATType = 6
	ThreeGPPRATType_Value_Virtual        ThreeGPPRATType = 7
	ThreeGPPRATType_Value_IEEE80216e     ThreeGPPRATType = 101
	ThreeGPPRATType_Value_ThreeGPP2EHRPD ThreeGPPRATType = 102
	ThreeGPPRATType_Value_ThreeGPP2HRPD  ThreeGPPRATType = 103
	ThreeGPPRATType_Value_ThreeGPP21xRTT ThreeGPPRATType = 104
	ThreeGPPRATType_Value_ThreeGPP2UMB   ThreeGPPRATType = 105
)

var ThreeGPPRATType_Strings = map[ThreeGPPRATType]string{
	ThreeGPPRATType_Value_Reserved:       "Reserved",
	ThreeGPPRATType_Value_UTRAN:          "UTRAN",
	ThreeGPPRATType_Value_GERAN:          "GERAN",
	ThreeGPPRATType_Value_WLAN:           "WLAN",
	ThreeGPPRATType_Value_GAN:            "GAN",
	ThreeGPPRATType_Value_HSPAEvolution:  "HSPA-Evolution",
	ThreeGPPRATType_Value_EUTRAN:         "EUTRAN",
	ThreeGPPRATType_Value_Virtual:        "Virtual",
	ThreeGPPRATType_Value_IEEE80216e:     "IEEE-802-16e",
	ThreeGPPRATType_Value_ThreeGPP2EHRPD: "3GPP2-eHRPD",
	ThreeGPPRATType_Value_ThreeGPP2HRPD:  "3GPP2-HRPD",
	ThreeGPPRATType_Value_ThreeGPP21xRTT: "3GPP2-1xRTT",
	ThreeGPPRATType_Value_ThreeGPP2UMB:   "3GPP2-UMB",
}

func (a ThreeGPPRATType) String() string {
	if str, ok := ThreeGPPRATType_Strings[a]; ok {
		return str
	}
	return "ThreeGPPRATType(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ThreeGPPRATType_Add(p *radius.Packet, value ThreeGPPRATType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_AddVendor(p, 21, a)
}

func ThreeGPPRATType_Get(p *radius.Packet) (value ThreeGPPRATType) {
	value, _ = ThreeGPPRATType_Lookup(p)
	return
}

func ThreeGPPRATType_Gets(p *radius.Packet) (values []ThreeGPPRATType, err error) {
	var i uint32
	for _, attr := range _ThreeGPP_GetsVendor(p, 21) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ThreeGPPRATType(i))
	}
	return
}

func ThreeGPPRATType_Lookup(p *radius.Packet) (value ThreeGPPRATType, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 21)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ThreeGPPRATType(i)
	return
}

func ThreeGPPRATType_Set(p *radius.Packet, value ThreeGPPRATType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_SetVendor(p, 21, a)
}

func ThreeGPPRATType_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 21)
}

func ThreeGPPUserLocationInfo_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 22, a)
}

func ThreeGPPUserLocationInfo_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 22, a)
}

func ThreeGPPUserLocationInfo_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPUserLocationInfo_Lookup(p)
	return
}

func ThreeGPPUserLocationInfo_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPUserLocationInfo_LookupString(p)
	return
}

func ThreeGPPUserLocationInfo_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 22) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPUserLocationInfo_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 22) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPUserLocationInfo_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 22)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPUserLocationInfo_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 22)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPUserLocationInfo_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 22, a)
}

func ThreeGPPUserLocationInfo_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 22, a)
}

func ThreeGPPUserLocationInfo_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 22)
}

func ThreeGPPMSTimeZone_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 23, a)
}

func ThreeGPPMSTimeZone_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 23, a)
}

func ThreeGPPMSTimeZone_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPMSTimeZone_Lookup(p)
	return
}

func ThreeGPPMSTimeZone_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPMSTimeZone_LookupString(p)
	return
}

func ThreeGPPMSTimeZone_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 23) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPMSTimeZone_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 23) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPMSTimeZone_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 23)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPMSTimeZone_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 23)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPMSTimeZone_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 23, a)
}

func ThreeGPPMSTimeZone_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 23, a)
}

func ThreeGPPMSTimeZone_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 23)
}

func ThreeGPPCamelChargingInfo_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 24, a)
}

func ThreeGPPCamelChargingInfo_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 24, a)
}

func ThreeGPPCamelChargingInfo_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPCamelChargingInfo_Lookup(p)
	return
}

func ThreeGPPCamelChargingInfo_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPCamelChargingInfo_LookupString(p)
	return
}

func ThreeGPPCamelChargingInfo_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 24) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPCamelChargingInfo_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 24) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPCamelChargingInfo_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPCamelChargingInfo_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPCamelChargingInfo_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 24, a)
}

func ThreeGPPCamelChargingInfo_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 24, a)
}

func ThreeGPPCamelChargingInfo_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 24)
}

func ThreeGPPPacketFilter_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 25, a)
}

func ThreeGPPPacketFilter_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_AddVendor(p, 25, a)
}

func ThreeGPPPacketFilter_Get(p *radius.Packet) (value []byte) {
	value, _ = ThreeGPPPacketFilter_Lookup(p)
	return
}

func ThreeGPPPacketFilter_GetString(p *radius.Packet) (value string) {
	value, _ = ThreeGPPPacketFilter_LookupString(p)
	return
}

func ThreeGPPPacketFilter_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _ThreeGPP_GetsVendor(p, 25) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPPacketFilter_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _ThreeGPP_GetsVendor(p, 25) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ThreeGPPPacketFilter_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 25)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ThreeGPPPacketFilter_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 25)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ThreeGPPPacketFilter_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 25, a)
}

func ThreeGPPPacketFilter_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _ThreeGPP_SetVendor(p, 25, a)
}

func ThreeGPPPacketFilter_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 25)
}

type ThreeGPPNegotiatedDSCP uint32

var ThreeGPPNegotiatedDSCP_Strings = map[ThreeGPPNegotiatedDSCP]string{}

func (a ThreeGPPNegotiatedDSCP) String() string {
	if str, ok := ThreeGPPNegotiatedDSCP_Strings[a]; ok {
		return str
	}
	return "ThreeGPPNegotiatedDSCP(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ThreeGPPNegotiatedDSCP_Add(p *radius.Packet, value ThreeGPPNegotiatedDSCP) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_AddVendor(p, 26, a)
}

func ThreeGPPNegotiatedDSCP_Get(p *radius.Packet) (value ThreeGPPNegotiatedDSCP) {
	value, _ = ThreeGPPNegotiatedDSCP_Lookup(p)
	return
}

func ThreeGPPNegotiatedDSCP_Gets(p *radius.Packet) (values []ThreeGPPNegotiatedDSCP, err error) {
	var i uint32
	for _, attr := range _ThreeGPP_GetsVendor(p, 26) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ThreeGPPNegotiatedDSCP(i))
	}
	return
}

func ThreeGPPNegotiatedDSCP_Lookup(p *radius.Packet) (value ThreeGPPNegotiatedDSCP, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 26)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ThreeGPPNegotiatedDSCP(i)
	return
}

func ThreeGPPNegotiatedDSCP_Set(p *radius.Packet, value ThreeGPPNegotiatedDSCP) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_SetVendor(p, 26, a)
}

func ThreeGPPNegotiatedDSCP_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 26)
}

type ThreeGPPAllocateIPType uint32

const (
	ThreeGPPAllocateIPType_Value_DoNotAllocateIPv4IPv6  ThreeGPPAllocateIPType = 0
	ThreeGPPAllocateIPType_Value_AllocateIPv4           ThreeGPPAllocateIPType = 1
	ThreeGPPAllocateIPType_Value_AllocateIPv6Prefix     ThreeGPPAllocateIPType = 2
	ThreeGPPAllocateIPType_Value_AllocateIPv4IPv6Prefix ThreeGPPAllocateIPType = 3
)

var ThreeGPPAllocateIPType_Strings = map[ThreeGPPAllocateIPType]string{
	ThreeGPPAllocateIPType_Value_DoNotAllocateIPv4IPv6:  "Do-Not-Allocate-IPv4-IPv6",
	ThreeGPPAllocateIPType_Value_AllocateIPv4:           "Allocate-IPv4",
	ThreeGPPAllocateIPType_Value_AllocateIPv6Prefix:     "Allocate-IPv6-Prefix",
	ThreeGPPAllocateIPType_Value_AllocateIPv4IPv6Prefix: "Allocate-IPv4-IPv6-Prefix",
}

func (a ThreeGPPAllocateIPType) String() string {
	if str, ok := ThreeGPPAllocateIPType_Strings[a]; ok {
		return str
	}
	return "ThreeGPPAllocateIPType(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ThreeGPPAllocateIPType_Add(p *radius.Packet, value ThreeGPPAllocateIPType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_AddVendor(p, 27, a)
}

func ThreeGPPAllocateIPType_Get(p *radius.Packet) (value ThreeGPPAllocateIPType) {
	value, _ = ThreeGPPAllocateIPType_Lookup(p)
	return
}

func ThreeGPPAllocateIPType_Gets(p *radius.Packet) (values []ThreeGPPAllocateIPType, err error) {
	var i uint32
	for _, attr := range _ThreeGPP_GetsVendor(p, 27) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ThreeGPPAllocateIPType(i))
	}
	return
}

func ThreeGPPAllocateIPType_Lookup(p *radius.Packet) (value ThreeGPPAllocateIPType, err error) {
	a, ok := _ThreeGPP_LookupVendor(p, 27)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ThreeGPPAllocateIPType(i)
	return
}

func ThreeGPPAllocateIPType_Set(p *radius.Packet, value ThreeGPPAllocateIPType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _ThreeGPP_SetVendor(p, 27, a)
}

func ThreeGPPAllocateIPType_Del(p *radius.Packet) {
	_ThreeGPP_DelVendor(p, 27)
}
